name: CUPS
version: "1.1"
slug: cupsik
description: A CUPS print server with working AirPrint and PDF generation
arch:
  - amd64
  - aarch64
usb: true
init: false
apparmor: false
homeassistant_api: true
host_network: true
ports:
  631/tcp: 631
  631/udp: 631
ports_description:
  631/tcp: For other devices on the local network to print to this server
  631/udp: For other devices on the local network to print to this server
# ingress: false

# experiment with a web UI for this:
#webui: http://[HOST]:[PORT:631]/admin

# /share added to receive PDFs and logs from the container
map:
  - config:rw
  - share:rw

# stage: experimental


